name: Starter Workflow

on:
  push:
    branches:
      - main
  issues: 
    types: 
      - openend
      - reopened
  schedule:
    - cron: '11 11 * * 5'
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'Environment to run tests against'
        type: string
        required: true 
    
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello world"
